### ISSUE TITLE
Mavericks Mock: java.lang.IllegalStateException: Method addObserver must be called on the main thread

### ISSUE THREAD

**Issue by ivanalvarado** [airbnb/mavericks#528]
The following exception is being thrown when I select a mocked Fragment from `MavericksLauncherActivity`.

> java.lang.IllegalStateException: Method addObserver must be called on the main thread
        at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
        at com.airbnb.mvrx.lifecycleAwareLazy.<init>(lifecycleAwareLazy.kt:29)
        at com.airbnb.mvrx.mocking.MockViewModelDelegateFactory.createLazyViewModel(MockViewModelDelegateFactory.kt:58)
        at com.ivanalvarado.maverickssample.ui.SampleFragment$$special$$inlined$fragmentViewModel$2.provideDelegate(ViewModelDelegateProvider.kt:23)
        at com.ivanalvarado.maverickssample.ui.SampleFragment$$special$$inlined$fragmentViewModel$2.provideDelegate(ViewModelDelegateProvider.kt:17)
        at com.ivanalvarado.maverickssample.ui.SampleFragment.<init>(SampleFragment.kt:71)

I followed the Mavericks setup from the [hellodagger](https://github.com/airbnb/mavericks/tree/master/hellodagger) package.

I have the following setup:

```
class SampleApplication : Application() {

    lateinit var appComponent: AppComponent

    override fun onCreate() {
        super.onCreate()
        appComponent = DaggerAppComponent.create()
        MockableMavericks.initialize(this)
    }
}

fun ComponentActivity.appComponent(): AppComponent {
    return (application as SampleApplication).appComponent
}
```

```
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        MavericksLauncherActivity.show(context = this)
    }
}
```

```
class SampleFragment : Fragment(), MockableMavericksView {

    private val viewModel: SampleViewModel by fragmentViewModel() // Exception is thrown here
    private val defaultState = SampleState(nameInput = "Ivan")
    ...

    override fun provideMocks() = mockSingleViewModel(
        viewModelReference = SampleFragment::viewModel,
        defaultState = defaultState,
        defaultArgs = null
    ) {}
}
```

```
data class SampleState(val nameInput: String = "") : MavericksState

class SampleViewModel @AssistedInject constructor(
    @Assisted state: SampleState
) : MavericksViewModel<SampleState>(state) {

    @AssistedFactory
    interface Factory : AssistedViewModelFactory<SampleViewModel, SampleState> {
        override fun create(state: SampleState): SampleViewModel
    }

    companion object :
        MavericksViewModelFactory<SampleViewModel, SampleState> by daggerMavericksViewModelFactory()
}
```

When I run the app, `MavericksLauncherActivity` does launch, but when I select `SampleFragment` from the list, the exception is thrown at `private val viewModel: SampleViewModel by fragmentViewModel()`.

**Any suggestions on troubleshooting?**

**Comment by ivanalvarado** [comment]
Never mind, I just noticed [this PR](https://github.com/airbnb/mavericks/pull/523).

**Comment by ivanalvarado** [comment]
**Update:** Fix changed in [this PR](https://github.com/airbnb/mavericks/pull/525).
