### ISSUE TITLE
possible incompatibility with Kotlin coroutines 1.7.0

### ISSUE THREAD

**Issue by kenyee** [airbnb/mavericks#677]
Using .flowWhenStarted() now throws this error:

```

java.lang.IllegalStateException: Flow invariant is violated:
  Emission from another coroutine is detected.
  Child of StandaloneCoroutine{Active}@ab35420, expected child of ScopeCoroutine{Active}@2bcc1d9.
  FlowCollector is not thread-safe and concurrent emissions are prohibited.
  To mitigate this restriction please use 'channelFlow' builder instead of 'flow'
 at kotlinx.coroutines.flow.internal.SafeCollector_commonKt$checkContext$result$1.invoke(SafeCollector.common.kt:68)
 at kotlinx.coroutines.flow.internal.SafeCollector_commonKt$checkContext$result$1.invoke(SafeCollector.common.kt:25)
 at kotlin.coroutines.CoroutineContext$Element$DefaultImpls.fold(CoroutineContext.kt:70)
 at kotlinx.coroutines.Job$DefaultImpls.fold(Job.kt:112)
 at kotlinx.coroutines.JobSupport.fold(JobSupport.kt:25)
 at kotlin.coroutines.CombinedContext.fold(CoroutineContextImpl.kt:131)
 at kotlinx.coroutines.flow.internal.SafeCollector_commonKt.checkContext(SafeCollector.common.kt:25)
 at kotlinx.coroutines.flow.internal.SafeCollector.checkContext(SafeCollector.kt:106)
 at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:83)
 at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
 at com.airbnb.mvrx.MavericksLifecycleAwareFlowKt$flowWhenStarted$1$1$transform$1.invokeSuspend(MavericksLifecycleAwareFlow.kt:36)
```

This is Mavericks version 3.0.1

**Comment by kenyee** [comment]
Also tried latest 3.0.2 and it has the same issue

**Comment by elihart** [comment]
Thanks for reporting. We don't currently plant to update coroutines support in the near future, but if someone wants to contribute a PR that'd be great

**Comment by ArunYogeshwaran** [comment]
Thanks a ton for this fix 🚀
